Update objects.py
Resolve issue with at_object_receive() now requiring move_type parameter:

 File "/root/evriftmud/evennia/evennia/objects/manager.py", line 573, in copy_object
    new_object = create.create_object(
  File "/root/evriftmud/evennia/evennia/objects/manager.py", line 734, in create_object
    new_object.save()
  File "/root/evriftmud/evennia/evennia/utils/idmapper/models.py", line 449, in save
    super().save(*args, **kwargs)
  File "/root/evriftmud/evenv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/root/evriftmud/evenv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/root/evriftmud/evenv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/root/evriftmud/evenv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/root/evriftmud/evennia/evennia/typeclasses/models.py", line 76, in call_at_first_save
    instance.at_first_save()
  File "/root/evriftmud/evennia/evennia/objects/objects.py", line 1493, in at_first_save
    cdict["location"].at_object_receive(self, None)
TypeError: Room.at_object_receive() missing 1 required positional argument: 'move_type'