Fix issue with helper func _on_monitor_change
This changes causes _on_monitor_change to first separate out the
category from the attribute field name in order to properly reference
the attribute on the object.  This fixes errors such as:

  File "C:\Users\Scyfris\Projects\norn\evennia\evennia\scripts\monitorhandler.py", line 118, in at_update
    callback(obj=obj, fieldname=fieldname, **kwargs)
  File "C:\Users\Scyfris\Projects\norn\evennia\evennia\server\inputfuncs.py", line 425, in _on_monitor_change
    callsign = {outputfunc_name: {"name": name, "value": _GA(obj, fieldname)}}
AttributeError: 'Attribute' object has no attribute 'db_value[base]'